// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using CoreGraphics;

namespace Demo2
{
	public partial class SecondViewController : UIViewController
	{
		public string value;
		public SecondViewController (IntPtr handle) : base (handle)
		{
			
		}
		public SecondViewController(){
			
		}
		public override void ViewDidLoad ()
		{
			label.Text = value;
		}
		public void recieveData(string text){

			Console.Write (text);

			value= text;


		}

	}
}
